### ISSUE TITLE
Implement asset search / filter

### ISSUE THREAD

**Issue by mattysmith22** [nottinghamtec/PyRIGS#345]
Ideally should be able to search by ID or name.

Filtering should be possible by category. Currently it is bugged, with a blank screen appearing upon the running of the JS

**Comment by FreneticScribbler** [comment]
Partially done. Search works. Filter works. You can't do both together. 
What you've searched/filtered isn't shown nicely either.

**Comment by mattysmith22** [comment]
Fixed in https://github.com/nottinghamtec/PyRIGS/commit/e3cbcbd1518e7ce51c0ab623f7ed9a35e5310d44 . Items can be searched by exact asset ID, or by contains in description. Filtering by category and status is also complete

**Comment by FreneticScribbler** [comment]
Still doesn't appear to work correctly on my end? All the issues I just listed seem present as of now. @mattysmith22

**Comment by mattysmith22** [comment]
I have double checked and while there were a few bugs in the functionality, it was there. Did you try the asset form branch?
